apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-jima
  namespace: qxgcdylz-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:5743462c1e03ce4bd700ff1ba8d6349108cff2c8b38a84451780704e53507e78
        name: my-java-quarkus
        resources: {}
status: {}
